---
brew_packages:
  casks:
    - amethyst
    - firefox
    - font-hack-nerd-font
    - google-chrome
    - kitty
    - rar
    - slack
    - telegram
    - vlc
    - zoom
  formulas:
    - ansible
    - autocannon
    - chafa
    - colima
    - deno
    - docker
    - docker-compose
    - fd
    - fzf
    - ghostscript
    - git
    - git-delta
    - gnupg
    - go
    - htop
    - imagemagick
    - iperf3
    - kubernetes-cli
    - lazygit
    - lefthook
    - llama.cpp
    - luarocks
    - mermaid-cli
    - minikube
    - n
    - neovim
    - nmap
    - prometheus
    - pure
    - python@3.13
    - ripgrep
    - ruby
    - rust
    - tectonic
    - tmux
    - tree
    - tree-sitter
    - tree-sitter-cli
    - vale
    - wget
    - zsh
    - zsh-autosuggestions
    - zsh-completions
  taps: []
git_config:
  user:
    name: 'Alexander Yamakin'
    email: '1650048+iamyamakin@users.noreply.github.com'
zsh_exports:
  - name: HOMEBREW_NO_ANALYTICS
    value: 1
  - name: N_PREFIX
    value: '$XDG_DATA_HOME/n'
  - name: RIPGREP_CONFIG_PATH
    value: '$XDG_CONFIG_HOME/ripgrep/ripgreprc'
...
